name: "Smoke test"
description: "Run smoke tests on the template"
inputs:
  template:
    description: "Template to test"
    required: true

runs:
  using: composite
  steps:
    - name: Checkout main
      id: checkout_release
      uses: actions/checkout@v3

    - name: Print file permissions
      id: print_file_permissions
      shell: bash
      run: ls -l ${{ github.action_path }}/build.sh

    - name: Add execute permissions to script
      id: add_execute_permissions
      shell: bash
      run: find . -name "*.sh" -exec chmod +x {} \;

    - name: Build template
      id: build_template
      shell: bash
      run: ${{ github.action_path }}/build.sh ${{ inputs.template }}

    - name: Test template
      id: test_template
      shell: bash
      run: ${{ github.action_path }}/test.sh  ${{ inputs.template }}
